{
 "title": "Positions",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Planes",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dump1090_lat", "legendFormat": "__auto" },
    { "expr": "dump1090_lon", "legendFormat": "__auto" },
    { "expr": "dump1090_heading", "legendFormat": "__auto" },
    { "expr": "dump1090_alt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spotted planes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (hex) (dump1090_lat))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Planes with registration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (reg) (dump1090_lat))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Planes with type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (type) (dump1090_lat))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Planes with position per receiver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_with_position",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most popular types",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(50, count by (type) (dump1090_lat{type!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Planes by country",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(50, count by (country) (label_replace(dump1090_lat{reg!=\"\"}, \"country\", \"$1\", \"reg\", \"(.*)-.+\")))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}